fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
      - id: check-ast
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
    -   id: serial-check
        name: Serial Check
        entry: SIEMENS-[A-Z0-9]+-(?!AB1234567890)[A-Z0-9]+
        language: pygrep
        types: [text]
