name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOMECONNECT_CLIENT_ID: ${{ vars.HOMECONNECT_CLIENT_ID }}
      HOMECONNECT_CLIENT_SECRET: ${{ secrets.HOMECONNECT_CLIENT_SECRET }}
      HOMECONNECT_REDIRECT_URI: ${{ vars.HOMECONNECT_REDIRECT_URI }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip3 install -e ".[dev]"

      - name: Run Pytest
        run: pytest
